version: '2.1'

services:
  lgy-iac-web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/dts-legacy/lgy-iac-web
    ports:
      - $SERVER_PORT:$SERVER_PORT
