server:
  port: 8080

logging:
  level:
    root: INFO
    org.flywaydb.core.Flyway: DEBUG

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

springdoc:
  packagesToScan: uk.gov.hmcts.legacy.web.controllers

env:
  dbhost: ${POSTGRES_HOST:localhost}
  dbport: ${POSTGRES_PORT:5432}
  dbname: ${POSTGRES_DATABASE:lgyiac}
  dbuser: ${POSTGRES_USER:lgyiacadmin}
  dbpass: ${POSTGRES_PASSWORD:dummy}

spring:
  config:
    import: "optional:configtree:/mnt/secrets/lgy-iac/"
  application:
    name: lgy-iac-web
  flyway:
    enabled: ${RUN_DB_MIGRATION_ON_STARTUP:false}
    baselineOnMigrate: true
    url: ${FLYWAY_URL:${spring.datasource.url}}
    user: ${FLYWAY_USER:${env.dbuser}}
    password: ${FLYWAY_PASSWORD:${env.dbpass}}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${env.dbhost}:${env.dbport}/${env.dbname}?sslmode=require
    username: ${env.dbname}
    password: ${env.dbpass}
    properties:
      charSet: UTF-8

dbMigration:
  # When true, the app will run DB migration on startup.
  # Otherwise, it will just check if all migrations have been applied (and fail to start if not).
  runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: smoke
  flyway:
    enabled: false
