package uk.gov.hmcts.legacy.web.selenium;

public interface ExpectedResults {

	public final String[][] IAFT1_Asylum_Payment_MultiAppeal_expectedResults ={ { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Immigration_Payment_MultiAppeal_expectedResults ={ { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Asylum_Payment_SingleAppeal_expectedResults ={ { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Asylum_Remission_SingleAppeal_expectedResults_LAC = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "LAC" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Asylum_Remission_SingleAppeal_expectedResults = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Asylum_Remission_MultiAppeal_expectedResults = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Immigration_Remission_SingleAppeal_expectedResults = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Immigration_Remission_MultiAppeal_expectedResults = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Immigration_Payment_SingleAppeal_expectedResults = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "No" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };

	public final String[][] IAFT1_Immigration_Remission_SingleAppeal_expectedResults_LAC = { { "hearing_type", "Oral" },
			{ "qa_sponsor", "Sponsor" }, { "qa_rep", "Representative" }, { "qa_witness", "Witness" },
			{ "qb_lsc", "LAC" }, { "qb_LAR", "123456789" }, { "family_member", "Yes" }, { "qc_name1", "Joe Joe" },
			{ "qc_relationship1", "Bro" }, { "qc_prn1", "1234-+" }, { "qc_name2", "Chad Chad" },
			{ "qc_relationship2", "Dad" }, { "qc_prn2", "ABCDabcd" }, { "qc_name3", "ANN ANN" },
			{ "qc_relationship3", "Gran" }, { "qc_prn3", "!^%$" }, { "qc_name4", "Roz Rox" },
			{ "qc_relationship4", "Cos" }, { "qc_prn4", "ABCD/1234" }, { "s1a", "Vader" }, { "s1b", "Darth" },
			{ "s1c", "Sith Lord" }, { "s1e", "Male" }, { "s1f_addr1", "1 Death Star" }, { "s1f_addr2", "Space" },
			{ "s1f_addr3", "Universe" }, { "s1f_addr4", "2:Albania" }, { "s1f_postcode", "OB1 WAN" },
			{ "s1g", "Sector7" }, { "s1h", "2:Albanian" }, { "s1i_yourself", "Yourself" },
			{ "s1i_witness", "Witnesses" }, { "s1i_representative", "Your representative" }, { "s1j", "Yes" },
			{ "s1j_who", "Protocol Droid C-3PO" }, { "s1j_language", "6Million" }, { "s1j_dialect", "Sith" },
			{ "s1k", "dummyText" }, { "s1l", "Yes" }, { "s1m", "01:05-AM" }, { "s1o", "Yes" }, { "s1q", "BB" },
			{ "s2a", "H12345" }, { "s2b", "APortRef/1234" }, { "s2c", "ACohidRef" }, { "s2d_post", "Fax" },
			{ "s2d_fax", "" }, { "s2d_courier", "" }, { "s2d_other", "AnotherName" }, { "s2f", "" }, { "s3a", "a" },
			{ "s3b", "b" }, { "s3c", "c" }, { "s3d_1", "a" }, { "s3d_2", "b" }, { "s3d_3", "c" }, { "s3d_4", "a" },
			{ "s3d_5", "b" }, { "s3d_6", "c" }, { "s3d_7", "d" }, { "s3d_8", "a" }, { "s3d_additional", "b" },
			{ "s3e", "Yes" }, { "s3e_appealno1", "A_REF1234" }, { "s3e_appealno2", "A_REF2345" },
			{ "s3e_appealno3", "A_REF4567" }, { "s3f", "" }, { "s4_signature", "" }, { "s4_date", "" },
			{ "s5a", "Judge Dredd" }, { "s5b", "554:A Bajwa and Co Solicitors" }, { "s5c_addr1", "22 Acacia Avenue" },
			{ "s5c_addr2", "X" }, { "s5c_addr3", "Y" }, { "s5c_addr4", "2:Albania" }, { "s5c_postcode", "123 ABC" },
			{ "s5d", "Please Write To Me" }, { "s5e", "1234567" }, { "s5f", "001234567" }, { "s5g", "0978786" },
			{ "s5h", "me@you.co.uk" }, { "s5i", "REF_123/456" }, { "s5j", "England and Wales" },
			{ "s5b_other", "Rhubarb & Custard" }, { "rep_sign", "Agreed" }, { "s4_declaration", "Appellant_agreed" } };
}
