java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  disableKeyVaults: true
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: 'true'
    FAVOURITE_FRUIT: IAC Fees Dev
