java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/lgy-iac/web:latest'
  ingressHost: lgy-iac-web.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: lgy-iac
  readinessPath: 'IACFees/health/liveness.do'
  livenessPath: 'IACFees/health/liveness.do'
  startupPath: 'IACFees/health/liveness.do'
  startupDelay: 20
  startupTimeout: 3
  startupPeriod: 60
  startupFailureThreshold: 5
  livenessDelay: 0
  smoketests:
    environment:
      TEST_URL: ${SERVICE_FQDN}/IACFees

  keyVaults:
    lgy-iac:
      resourceGroup: lgy-iac-{{ .Values.global.environment }}
      secrets:
        - name: web-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: web-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: web-POSTGRES-USER
          alias: POSTGRES_USER
        - name: web-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
  environment:
    ENV_NAME: "Azure Dev PG"
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    EPDQ_PSPID: "a"
    EPDQ_URL: "b"
    EPDQ_SHAIN: "c"
    EPDQ_SHAOUT: "d"
    TEST_URL: ${SERVICE_FQDN}/IACFees
    STORAGE_METHOD: "file" // change to S3 or BLOB to test uploading to AWS or Azure

