# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  environment:
    ENV_NAME: "Azure Stg PG"
    FLYWAY_USER: ${FLYWAY_USER}
    FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
    FLYWAY_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?&sslmode=require
    POSTGRES_HOST: "value_from_stg.template"
    POSTGRES_PORT: "5432"
    POSTGRES_DATABASE: ${db_database}
    POSTGRES_USER: ${db_user}
    POSTGRES_PASSWORD: ${db_password}
    POSTGRES_SSL_MODE: require
    DB_JDBC_DRIVER: "org.postgresql.Driver"
    DB_JDBC_URL: "jdbc:postgresql"
