java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/lgy-iac/web:latest'
  ingressHost: lgy-iac-web.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: lgy-iac
  keyVaults:
    lgy-iac:
      resourceGroup: lgy-iac-{{ .Values.global.environment }}
      secrets:
        - name: web-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: web-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: web-POSTGRES-USER
          alias: POSTGRES_USER
        - name: web-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
  environment:
    POSTGRES_SSL_MODE: require
    FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?&sslmode=require
    FLYWAY_USER: ${POSTGRES_USER}
    FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    FAVOURITE_FRUIT: IAC Fees Default
    RUN_DB_MIGRATION_ON_STARTUP: 'false'

