java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/lgy-iac/web:latest'
  ingressHost: lgy-iac-web.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: lgy-iac
  keyVaults:
    lgy-iac:
      resourceGroup: lgy-iac-{{ .Values.global.environment }}
      secrets:
        - name: web-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: web-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: web-POSTGRES-USER
          alias: POSTGRES_USER
        - name: web-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
  environment:
    POSTGRES_SSL_MODE: require
    FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?&sslmode=require
    FLYWAY_USER: ${POSTGRES_USER}
    FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    ENV_NAME: "Azure Staging PG"
    DB_JDBC_DRIVER: "org.postgresql.Driver"
    DB_JDBC_URL: "jdbc:postgresql"
    DB_HOST: ${POSTGRES_HOST}
    DB_PORT: "5432"
    DB_USER: ${POSTGRES_USER}
    DB_PASSWORD: ${POSTGRES_PASSWORD}
    DB_NAME: ${POSTGRES_DATABASE}
    EPDQ_PSPID: "a"
    EPDQ_URL: "b"
    EPDQ_SHAIN: "c"
    EPDQ_SHAOUT: "d"


