java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  disableKeyVaults: false
  environment:
    FAVOURITE_FRUIT: IAC Fees Dev
    RUN_DB_MIGRATION_ON_STARTUP: 'true'
    RUN_DB_REPAIR_ON_STARTUP: 'true'
    FLYWAY_USER: ${FLYWAY_USER}
    FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
    FLYWAY_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?&sslmode=require
    POSTGRES_HOST: ${DB_HOST}
    POSTGRES_PORT: "5432"
    POSTGRES_DATABASE: ${DB_DATABASE}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_SSL_MODE: require
    DB_JDBC_DRIVER: "org.postgresql.Driver"
    DB_JDBC_URL: "jdbc:postgresql"
