java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/lgy-iac/web:latest'
  #need to set ingressHost in sds-flux-config for each env(stg.yaml)
  ingressHost: lgy-iac-web.staging.platform.hmcts.net
  aadIdentityName: lgy-iac
  keyVaults:
    lgy-iac:
      resourceGroup: lgy-iac-{{ .Values.global.environment }}
      secrets:
        - name: web-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: web-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: web-POSTGRES-USER
          alias: POSTGRES_USER
        - name: web-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
  environment:
    POSTGRES_SSL_MODE: require
    FLYWAY_URL: jdbc:postgresql://lgy-iac-v11-{{ .Values.global.environment }}.postgres.database.azure.com:5432/lgyiac?&sslmode=require
    FLYWAY_USER: lgyiacadmin@lgy-iac-v11-{{ .Values.global.environment }}
    FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    FAVOURITE_FRUIT: IAC Fees Default
    RUN_DB_MIGRATION_ON_STARTUP: false

