java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/lgy-iac/web:latest'
  ingressHost: lgy-iac-web.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: lgy-iac
  readinessPath: 'IACFees/health/liveness.do'
  livenessPath: 'IACFees/health/liveness.do'
  startupPath: 'IACFees/health/liveness.do'
  startupDelay: 20
  startupTimeout: 3
  startupPeriod: 60
  startupFailureThreshold: 5
  livenessDelay: 0
  smoketests:
    environment:
      TEST_URL: ${SERVICE_FQDN}/IACFees

  keyVaults:
    lgy-iac:
      resourceGroup: lgy-iac-{{ .Values.global.environment }}
      secrets:
        - name: web-POSTGRES-DATABASE
          alias: DB_NAME
        - name: web-POSTGRES-HOST
          alias: DB_HOST
        - name: web-POSTGRES-USER
          alias: DB_USER
        - name: web-POSTGRES-PASS
          alias: DB_PASSWORD

  environment:
    POSTGRES_SSL_MODE: require
    FLYWAY_URL: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?&sslmode=require
    FLYWAY_USER: ${POSTGRES_USER}
    FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    ENV_NAME: "Azure Dev PG"
    DB_JDBC_DRIVER: "org.postgresql.Driver"
    DB_JDBC_URL: "jdbc:postgresql"
    DB_PORT: "5432"
    EPDQ_PSPID: "a"
    EPDQ_URL: "b"
    EPDQ_SHAIN: "c"
    EPDQ_SHAOUT: "d"
    TEST_URL: ${SERVICE_FQDN}/IACFees


